
# platform :ios, '9.0'

target 'AdRenalin' do
    
    use_frameworks!
    
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'ObjectMapper'
    pod 'AlamofireObjectMapper'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
    
end
